name: tracker
description: A task manager written using Polymer
dependencies:
  polymer: ">=0.15.0 <0.16.0"
transformers:
- polymer:
    entry_points: web/index.html
environment:
  sdk: ">=0.8.10+6 <2.0.0"
